name: Build

on:
  push:
  pull_request:

jobs:

  build-base:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check out code
        uses: actions/checkout@v1

      - name: Check version details
        id: info
        run: |
          echo ::set-output name=IMAGE::quay.io/acoustid/chromaprint-build-base
          if [[ $GITHUB_REF == refs/tags/v* ]]
          then
            echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d'/' -f3 | sed 's/^v//')
          else
            echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d'/' -f3)
          fi

      - uses: whoan/docker-build-with-cache-action@v3
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          image_name: ${{ steps.info.outputs.IMAGE }}
          image_tag: ${{ steps.info.outputs.VERSION }}
          registry: quay.io
