name: Build

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base:
          - manylinux2010
          - xenial
          - alpine

    steps:
    
      - name: Check out code
        uses: actions/checkout@v1

      - name: Check version details
        id: info
        run: |
          echo ::set-output name=IMAGE::quay.io/acoustid/chromaprint-build-base
          if [[ $GITHUB_REF == refs/tags/v* ]]
          then
            echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d'/' -f3 | sed 's/^v//')
          else
            echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d'/' -f3)
          fi

      - name: Build image
        run: |
          cd ${{ matrix.base }}
          docker build -t ${{ steps.info.outputs.IMAGE }}:${{ steps.info.outputs.VERSION }}-${{ matrix.base }} .

      - name: Push image
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
          docker push ${{ steps.info.outputs.IMAGE }}:${{ steps.info.outputs.VERSION }}-${{ matrix.base }}
          if [ $VERSION = master ]
          then
              docker tag ${{ steps.info.outputs.IMAGE }}:${{ steps.info.outputs.VERSION }}-${{ matrix.base }} ${{ steps.info.outputs.IMAGE }}:${{ matrix.base }}
              docker push ${{ steps.info.outputs.IMAGE }}:${{ matrix.base }}
          fi
